---
name: Test & Build

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml

  coverage:
    uses: ./.github/workflows/coverage.yml
    secrets: inherit

  security:
    uses: ./.github/workflows/security-audit.yml

  containers:
    uses: ./.github/workflows/containers.yml

  build:
    name: Build (${{ matrix.build }})
    runs-on: ${{ matrix.os }}
    needs:
      - test
      - containers

    strategy:
      matrix:
        include:
          - build: linux-default
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            feature-set: default

          - build: linux-telemetry
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            feature-set: telemetry

          - build: macos-default
            os: macos-latest
            target: x86_64-apple-darwin
            feature-set: default

          - build: macos-telemetry
            os: macos-latest
            target: x86_64-apple-darwin
            feature-set: telemetry

          - build: windows-default
            os: windows-latest
            target: x86_64-pc-windows-msvc
            feature-set: default

          - build: windows-telemetry
            os: windows-latest
            target: x86_64-pc-windows-msvc
            feature-set: telemetry

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Get package name from Cargo.toml
        id: package
        shell: bash
        run: |
          PACKAGE_NAME=$(awk -F '"' '/^name = / {print $2; exit}' Cargo.toml)
          echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "Package name: $PACKAGE_NAME"

      - name: Branch name
        shell: bash
        run: echo "${GITHUB_REF##*/}"

      - name: Get the release version from the tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - run: sudo apt -y install musl-dev musl-tools
        if: startsWith(matrix.build, 'linux-')

      - name: Build (${{ matrix.feature-set }})
        if: matrix.feature-set == 'default'
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Build (telemetry)
        if: matrix.feature-set == 'telemetry'
        run: cargo build --release --locked --target ${{ matrix.target }} --features telemetry
